name: "Get Changed Files"

on:
  workflow_dispatch:

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get list of changed files
      uses: lots0logs/gh-action-get-changed-files@v1
      id: changed-files
      with:
        format: json

    - name: Output changed files
      run: |
        echo "Changed files:"
        echo "${{ steps.changed-files.outputs.files }}"
