name: "Get Changed Files"

on:
  workflow_dispatch:

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get list of changed files
      id: changed-files
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
        git diff --name-only origin/${{ github.event.pull_request.base.ref }} > changed_files.txt
        echo "changed_files=$(cat changed_files.txt)" >> $GITHUB_ENV

    - name: Output changed files
      run: |
        echo "Changed files:"
        echo "${{ env.changed_files }}"
