name: "Get Changed Files"

on:
  workflow_dispatch:

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get list of changed files
      uses: lots0logs/gh-action-get-changed-files@2.2.2
      id: changed-files
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Output changed files
      run: |
        echo "Changed files:"
        echo "${HOME}/file.json"
        cat "${HOME}/file.json"
